### PR TITLE
convert to ASCII encoding

### PR DESCRIPTION
**Pull request by gizero**
* weird UTF-8 encoded chars were driving Vim crazily complaining that 'finish'
was not a valid editor command
* At every run of PluginInstall command, the 'already loaded' test
at the beginning of the script was failing, causing the rest of the script
to be executed anyway
* code in the original vivien/vim-linux-coding-style was not affected while
bhilburn/kernel-coding-style you forked from indeed was

### CODE REVIEW

**Comment by gregkh** [comment]
You only changed one thing here, yet you list 3 changes in your pull request, am I missing some other patches here?

And this is just a fork from upstream, hopefully they take my original changes someday, I don't want to maintain this for forever :)

**Comment by gizero** [comment]
Hi! No other patches... just changed that one line! I see you forked from an upstream project but I noticed your repo and your direct upstream is affected, while the original by @vivien is not. I might reword my comment and send the same PR to @bhilburn also.

**Comment by bhilburn** [comment]
Whoa. I honestly did not know that PR was sitting there - and it was 1.5 years old! Sorry, @gregkh! I have merged the PR. 

@gizero - Feel free to submit against my fork, and I'll merge immediately.

**Comment by vivien** [comment]
@d-k-c already added the highlighting of __* variables, then added the support for conditional activation. I bumped the official version in both [Github](https://github.com/vivien/vim-linux-coding-style) and [vim.org](http://www.vim.org/scripts/script.php?script_id=4369). Thanks for mentioning @gizero.

**Comment by gizero** [comment]
closing this since @vivien merged pending PRs, @bhilburn apparently dropped his fork. I'm fine with current upstream! ;-)

**Pull request closed without merging**
